apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpacpuram
  namespace: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20