apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisk
  name: redis
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  
